### ISSUE TITLE
%pokelearns renders Pokemon unable to be called

### ISSUE THREAD

**Issue by augur0** [XShadeSlayerXx/PokeRole-Discord.py-Base#25]
In this example, calling %pokelearns pansear initially returns a list of moves, while calling it again returns an error message.

![image](https://user-images.githubusercontent.com/66222736/93255265-aa5af000-f767-11ea-8d23-f5e4f31a3786.png)

**Comment by augur0** [comment]
Forgot to test initially, but this issue is likely connected to errors I have been having.
-%stats is unaffected
-_%ability cannot find any Pokemon to begin with_ %ability is meant to be used with abilities, my bad

This issue comes up mostly in %encounter, and may be affecting biomes and %filterhabitat behind the scenes?

The call %encounter 1 base pansear shows nothing after having previously called %pokelearns pansear:
![image](https://user-images.githubusercontent.com/66222736/93255837-7633ff00-f768-11ea-90d2-b1535b1ea280.png)

**Comment by XShadeSlayerXx** [comment]
Issue related to the pokelearns function making a shallow copy, when it used to make deep copies. Fixed.
