### ISSUE TITLE
Can I use your csv data?

### ISSUE THREAD

**Issue by Jacudibu** [XShadeSlayerXx/PokeRole-Discord.py-Base#42]
Hey, I'm currently creating my own discord bot for my D&D Friends as a little programming exercise. We were planning to use the Pokerole system, but want to do a lot of custom modifications to the base rules in order to fit it our setting a bit better.

Is it okay for you if I use your CSV data as a baseline for all of it?
Might also be able to contribute new Pokemon or moves, if they ever get added to the rulebook. :)

**Comment by XShadeSlayerXx** [comment]
Of course! Feel free to use and/or contribute to the repo

**Comment by Jacudibu** [comment]
Alright, thanks! :)
