### ISSUE TITLE
Typo - Hydro Cannon and Mirror Shot

### ISSUE THREAD

**Issue by UsrnamePending** [XShadeSlayerXx/PokeRole-Discord.py-Base#44]
'The user needs to res afterwards.' should be Rest

There's a large number of these scattered amongst the various moves but I just stumbled upon this one while gming
![image](https://github.com/XShadeSlayerXx/PokeRole-Discord.py-Base/assets/128330781/96324d0a-d9fe-4cb7-8444-38ceb0955466)

**Comment by UsrnamePending** [comment]
![image](https://github.com/XShadeSlayerXx/PokeRole-Discord.py-Base/assets/128330781/e6f30a95-3c3b-4922-858d-79b9ea557487)
Another example

**Comment by XShadeSlayerXx** [comment]
fixed, thank you
